/* eslint-disable no-irregular-whitespace, @typescript-eslint/no-unused-vars */
import { useState, type ReactNode } from 'react';
import { useLocation } from 'react-router-dom';
import styles from './PlatformPage.module.css';
import { DataManagementV11 } from './newPrototype/DataManagementV11';
import { EnergyAnalysisV4 } from './newPrototype/EnergyAnalysisV4';
import { CarbonAccountingV4 } from './newPrototype/CarbonAccountingV4';
import { AssetOperationsV2 } from './newPrototype/AssetOperationsV2';
import { DataCollectionPage } from './newPrototype/DataCollectionPage';

type Row = Record<string, ReactNode>;
type ActionKind = 'add' | 'edit' | 'view' | 'budget' | 'asset' | 'estimate' | 'factor';

const units = ['生产单元A', '生产单元B', '公辅系统', '回收能源系统', '辅助车间'];
const energyTypes = ['电力', '煤炭', '天然气', '热力', '替代燃料'];
const consumptionRows: Row[] = units.map((unit, index) => ({ unit, level: index < 2 ? '一级' : '二级', category: index < 2 ? '生产单元' : '公辅系统', energy: energyTypes[index], unitName: index % 2 ? 't' : 'tce', progress: `${78 - index * 8}%`, total: (6320 - index * 540).toLocaleString() }));
const inventoryRows: Row[] = [
  { type: '固定燃烧源', source: '天然气燃烧（锅炉房）', activity: '120,000 Nm³', origin: '能源数据', emission: '258.40', group: '化石燃料燃烧排放', missing: '' },
  { type: '移动燃烧源', source: '柴油燃烧（厂内车辆）', activity: '15.6 t', origin: '能源数据', emission: '48.30', group: '化石燃料燃烧排放', missing: '' },
  { type: '生产过程排放', source: '水泥熟料生产回转窑', activity: '待录入', origin: '在线录入', emission: '—', group: '生产过程排放', missing: '待补充' },
  { type: '逸散排放', source: '制冷剂R134a补充', activity: '120 kg', origin: '在线录入', emission: '171.60', group: '逸散排放', missing: '' },
  { type: '购入电力', source: '外购电力（企业整体）', activity: '18,600 MWh', origin: '能源数据', emission: '10,607.58', group: '购入的电力与热力产生的排放', missing: '' },
];
const factorRows: Row[] = [
  { name: '天然气（锅炉）', energy: '天然气', source: '固定燃烧源', standard: 'GB/T 32151-2023', type: '默认因子', unit: 'tCO₂/10⁴m³', value: '20.44', range: '全国', state: '启用' },
  { name: '标准煤（燃烧）', energy: '煤炭', source: '固定燃烧源', standard: 'GB/T 32151-2023', type: '默认因子', unit: 'tCO₂/t', value: '2.42', range: '全国', state: '启用' },
  { name: '柴油（燃烧）', energy: '柴油', source: '固定燃烧源', standard: 'GB/T 32151-2023', type: '默认因子', unit: 'tCO₂/t', value: '3.17', range: '全国', state: '启用' },
  { name: '外购电力（华东）', energy: '电力', source: '外购电力', standard: '生态环境部公告', type: '默认因子', unit: 'tCO₂/MWh', value: '0.7035', range: '华东地区', state: '启用' },
  { name: '天然气（企业实测）', energy: '天然气', source: '固定燃烧源', standard: '企业实测', type: '实测因子', unit: 'tCO₂/10⁴m³', value: '19.86', range: '某某水泥厂', state: '启用' },
];

function Button({ children, primary = false, onClick, className = '', type = 'button' }: { children: ReactNode; primary?: boolean; onClick?: () => void; className?: string; type?: 'button' | 'submit' }) {
  return <button type={type} onClick={onClick} className={`${styles.button} ${primary ? styles.primary : ''} ${className}`}>{children}</button>;
}
function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`${styles.card} ${className}`}>{children}</section>; }
function Tag({ children, tone = 'green' }: { children: ReactNode; tone?: 'green' | 'red' | 'orange' | 'blue' | 'gray' }) { return <span className={`${styles.tag} ${styles[`tag${tone}`]}`}>{children}</span>; }
function FilterBar({ children, onQuery, onReset, extra }: { children: ReactNode; onQuery?: () => void; onReset?: () => void; extra?: ReactNode }) { return <Card className={styles.filterBar}><div className={styles.filterFields}>{children}</div><div className={styles.filterActions}>{onQuery && <Button primary onClick={onQuery}>查询</Button>}{onReset && <Button onClick={onReset}>重置</Button>}{extra}</div></Card>; }
function Kpi({ icon, label, value, unit, sub, tone = 'green' }: { icon: string; label: string; value: string; unit: string; sub?: ReactNode; tone?: string }) { return <div className={`${styles.kpi} ${styles[`kpi${tone}`]}`}><div className={styles.kpiIcon}>{icon}</div><div><div className={styles.kpiLabel}>{label}</div><strong>{value}<small>{unit}</small></strong>{sub && <div className={styles.kpiSub}>{sub}</div>}</div></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className={styles.field}><span>{label}</span>{children}</label>; }
function Select({ children, value, onChange }: { children: ReactNode; value?: string; onChange?: (value: string) => void }) { return <select value={value} onChange={(e) => onChange?.(e.target.value)}>{children}</select>; }
function Table({ headers, rows, onRow, rowClass }: { headers: string[]; rows: Row[]; onRow?: (row: Row) => void; rowClass?: (row: Row) => string }) { return <div className={styles.tableWrap}><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={`${String(row.id ?? row.name ?? row.source ?? row.unit ?? i)}`} className={rowClass?.(row)} onClick={() => onRow?.(row)}>{Object.values(row).map((value, j) => <td key={j}>{typeof value === 'string' && value.startsWith('+') ? <span className={styles.negative}>{value}</span> : value}</td>)}</tr>)}</tbody></table></div>; }
function SectionTitle({ children, action }: { children: ReactNode; action?: ReactNode }) { return <div className={styles.sectionTitle}><h2>{children}</h2>{action}</div>; }
function Tabs({ items, active, onChange }: { items: string[]; active: string; onChange: (item: string) => void }) { return <div className={styles.tabs}>{items.map((item) => <button type="button" key={item} className={active === item ? styles.tabActive : ''} onClick={() => onChange(item)}>{item}</button>)}</div>; }
function Donut({ values, colors, center, labels }: { values: number[]; colors: string[]; center: string; labels: string[] }) { const total = values.reduce((sum, value) => sum + value, 0); return <div className={styles.donutBox}><svg viewBox="0 0 120 120" className={styles.donut}><circle cx="60" cy="60" r="41" fill="none" stroke="#edf1f3" strokeWidth="17" />{values.map((value, i) => { const dash = `${(value / total) * 257} 257`; const offset = values.slice(0, i).reduce((sum, item) => sum + (item / total) * 257, 0); return <circle key={labels[i]} cx="60" cy="60" r="41" fill="none" stroke={colors[i]} strokeWidth="17" strokeDasharray={dash} strokeDashoffset={-offset} transform="rotate(-90 60 60)" />; })}<text x="60" y="58" textAnchor="middle" className={styles.donutText}>{center}</text><text x="60" y="72" textAnchor="middle" className={styles.donutUnit}>tce</text></svg><div className={styles.legend}>{labels.map((label, i) => <div key={label}><i style={{ background: colors[i] }} />{label}<b>{Math.round(values[i] / total * 100)}%</b></div>)}</div></div>; }
function BarChart({ values, labels, color = '#08a66c' }: { values: number[]; labels: string[]; color?: string }) { const max = Math.max(...values); return <div className={styles.barChart}>{values.map((value, i) => <div className={styles.barItem} key={labels[i]}><strong>{value.toLocaleString()}</strong><div className={styles.barTrack}><span style={{ height: `${Math.max(8, value / max * 100)}%`, background: color }} /></div><small>{labels[i]}</small></div>)}</div>; }
function LineChart({ actual, forecast, target, labels, color = '#08a66c' }: { actual: number[]; forecast?: number[]; target?: number; labels: string[]; color?: string }) { const max = Math.max(...actual, ...(forecast ?? []), target ?? 0) * 1.18; const line = (values: number[], start = 0) => values.map((value, i) => `${8 + ((labels.length - 1) ? (i + start) / (labels.length - 1) * 84 : 0)},${85 - value / max * 70}`).join(' '); return <div className={styles.lineChart}><svg viewBox="0 0 100 100" preserveAspectRatio="none"><g className={styles.gridLines}>{[15, 38, 61, 85].map((y) => <line key={y} x1="7" x2="94" y1={y} y2={y} />)}</g>{target && <line x1="7" x2="94" y1={85 - target / max * 70} y2={85 - target / max * 70} className={styles.targetLine} />}{actual.length > 1 && <polyline points={line(actual)} fill="none" stroke={color} strokeWidth="1.8" />}{forecast && <polyline points={line(forecast, actual.length - 1)} fill="none" stroke="#2878ff" strokeWidth="1.8" strokeDasharray="3 2" />}{actual.map((value, i) => <circle key={i} cx={8 + i / (labels.length - 1) * 84} cy={85 - value / max * 70} r="1.7" fill={color} />)}</svg><div className={styles.axis}>{labels.map((label) => <span key={label}>{label}</span>)}</div></div>; }
function FlowDiagram() { return <div className={styles.flowDiagram}><div className={`${styles.flowNode} ${styles.flowInput}`}><b>能源输入量</b><strong>13,320</strong><small>tce</small></div><div className={styles.flowLinks}><span /><span /><span /><span /></div><div className={styles.flowColumns}><div><div className={styles.flowNode}>外购电力<br /><strong>6,127</strong></div><div className={styles.flowNode}>天然气<br /><strong>4,256</strong></div><div className={styles.flowNode}>原煤<br /><strong>1,999</strong></div></div><div><div className={`${styles.flowNode} ${styles.flowOrange}`}>余热发电系统<br /><strong>960</strong></div><div className={`${styles.flowNode} ${styles.flowOrange}`}>燃气锅炉<br /><strong>1,880</strong></div><div className={`${styles.flowNode} ${styles.flowOrange}`}>回收热水利用<br /><strong>320</strong></div></div><div><div className={`${styles.flowNode} ${styles.flowGreen}`}>生产单元A<br /><strong>6,220</strong></div><div className={`${styles.flowNode} ${styles.flowGreen}`}>生产单元B<br /><strong>3,480</strong></div><div className={`${styles.flowNode} ${styles.flowGreen}`}>公辅系统<br /><strong>2,300</strong></div></div><div><div className={`${styles.flowNode} ${styles.flowPurple}`}>企业外部<br /><strong>340</strong></div><div className={styles.flowNode}>未分配能源量<br /><strong>340</strong></div></div></div></div>; }
function EmptyScope({ title, description }: { title: string; description: string }) { return <Card className={styles.scopeCard}><div className={styles.scopeIcon}>▤</div><h2>{title}</h2><p>{description}</p><Button onClick={() => undefined}>返回核算清单</Button></Card>; }

function Modal({ title, children, onClose, onSave }: { title: string; children: ReactNode; onClose: () => void; onSave?: () => void }) { return <div className={styles.overlay} onMouseDown={(e) => e.target === e.currentTarget && onClose()}><div className={styles.modal}><div className={styles.modalHead}><h2>{title}</h2><button onClick={onClose} type="button">×</button></div><form className={styles.modalBody} onSubmit={(event) => { event.preventDefault(); if (event.currentTarget.reportValidity()) onSave?.(); }}>{children}<div className={styles.modalFoot}><Button onClick={onClose}>取消</Button>{onSave && <Button primary type="submit">保存</Button>}</div></form></div></div>; }
function Drawer({ title, children, onClose, footer }: { title: string; children: ReactNode; onClose: () => void; footer?: ReactNode }) { return <div className={styles.overlay} onMouseDown={(e) => e.target === e.currentTarget && onClose()}><aside className={styles.drawer}><div className={styles.modalHead}><h2>{title}</h2><button onClick={onClose} type="button">×</button></div><div className={styles.drawerBody}>{children}</div><div className={styles.modalFoot}>{footer ?? <Button onClick={onClose}>关闭</Button>}</div></aside></div>; }
function ContextModalFields({ kind }: { kind: ActionKind }) {
  if (kind === 'budget') return <><div className={styles.formIntro}>配置年度预算目标及预警阈值，保存后用于预算执行趋势与偏差判断。</div><div className={styles.formGrid}><Field label="预算类型"><Select><option>能源预算</option><option>碳排放预算</option></Select></Field><Field label="管理周期"><Select><option>2026年度</option><option>2027年度</option></Select></Field><Field label="统计范围"><Select><option>全企业</option><option>生产单元A</option></Select></Field><Field label="年度目标"><input required placeholder="请输入年度目标" /></Field><Field label="预警阈值"><input required defaultValue="95%" /></Field><Field label="单位"><Select><option>tce</option><option>tCO₂</option></Select></Field><Field label="配置说明"><textarea placeholder="请输入预算目标配置说明" /></Field></div></>;
  if (kind === 'asset') return <><div className={styles.formIntro}>录入当前履约周期内可使用的碳配额、CCER或其他碳资产。</div><div className={styles.formGrid}><Field label="资产类型"><Select><option>碳配额</option><option>CCER</option><option>绿证折算减排量</option></Select></Field><Field label="履约周期"><Select><option>2026年度</option></Select></Field><Field label="资产来源"><Select><option>政府分配</option><option>市场购买</option><option>内部转化</option></Select></Field><Field label="资产数量"><input required placeholder="请输入数量" /></Field><Field label="入账日期"><input required type="date" defaultValue="2026-06-30" /></Field><Field label="凭证编号"><input placeholder="请输入凭证编号" /></Field><Field label="备注"><textarea placeholder="请输入碳资产说明" /></Field></div></>;
  if (kind === 'estimate') return <><div className={styles.formIntro}>依据已确认的历史排放和本周期变化参数进行展示性测算，不新增未确认公式。</div><div className={styles.formGrid}><Field label="基准期"><Select><option>2023—2025年</option></Select></Field><Field label="新履约周期"><Select><option>2027年度</option></Select></Field><Field label="基准历史排放"><input required defaultValue="98,500" /></Field><Field label="预计产量变化"><input required defaultValue="+1.1%" /></Field><Field label="初步测算配额"><input required defaultValue="96,000" /></Field><Field label="单位"><Select><option>tCO₂</option></Select></Field><Field label="测算说明"><textarea defaultValue="测算结果仅用于原型演示，最终配额以主管部门核定为准。" /></Field></div></>;
  if (kind === 'factor') return <><div className={styles.formIntro}>为排放源选择核算使用的碳排放因子，因子字段与碳因子库保持一致。</div><div className={styles.formGrid}><Field label="排放源名称"><input required defaultValue="天然气燃烧（锅炉房）" /></Field><Field label="活动数据"><input required defaultValue="120,000 Nm³" /></Field></div><div className={styles.factorPicker}><b>选择碳排放因子</b><label className={styles.factorSelected}><input type="radio" name="factor" defaultChecked /><span><strong>天然气（锅炉）</strong><small>GB/T 32151-2023　20.44 tCO₂/10⁴m³</small></span><Tag>推荐</Tag></label><label><input type="radio" name="factor" /><span><strong>天然气（企业实测）</strong><small>企业实测　19.86 tCO₂/10⁴m³</small></span><Tag tone="orange">实测</Tag></label><label><input type="radio" name="factor" /><span><strong>天然气（区域因子）</strong><small>区域数据库　20.12 tCO₂/10⁴m³</small></span><Tag tone="blue">区域</Tag></label></div></>;
  return <div className={styles.formGrid}><Field label="名称"><input autoFocus required placeholder="请输入名称" /></Field><Field label="所属范围"><Select><option>全企业</option><option>生产单元A</option></Select></Field><Field label="年度"><Select><option>2026</option><option>2025</option></Select></Field><Field label="备注"><textarea placeholder="请输入备注" /></Field></div>;
}

export function PlatformPage() {
  const { pathname } = useLocation();
  const [toast, setToast] = useState('');
  const [activeTab, setActiveTab] = useState('能源消费');
  const [modal, setModal] = useState<ActionKind | null>(null);
  const [drawer, setDrawer] = useState<Row | null>(null);
  const [rows, setRows] = useState<Row[]>(consumptionRows);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 1800); };
  const routeTab = pathname.includes('energy-costs') ? '能源成本' : pathname.includes('energy-relations') ? '特殊能源关系' : activeTab;
  const common = { notify, openModal: (kind: ActionKind) => setModal(kind), openDrawer: (row: Row) => setDrawer(row), closeDrawer: () => setDrawer(null), rows, setRows };
  let content: ReactNode;
  if (pathname.startsWith('/data-management/')) content = <DataManagementV11 key={pathname} pathname={pathname} />;
  else if (pathname.startsWith('/energy-analysis/')) content = <EnergyAnalysisV4 pathname={pathname} />;
  else if (pathname.startsWith('/carbon-accounting/')) content = <CarbonAccountingV4 pathname={pathname} />;
  else if (pathname.startsWith('/asset-strategy/')) content = <AssetOperationsV2 pathname={pathname} />;
  else if (pathname.startsWith('/data-collection/')) content = <DataCollectionPage />;
  else content = <DataCollectionPage />;
  const modalTitle = modal === 'budget' ? '目标预算配置' : modal === 'asset' ? '录入碳资产' : modal === 'estimate' ? '新履约周期配额测算' : modal === 'factor' ? '碳排放因子选择' : modal === 'add' ? '新增记录' : '编辑记录';
  const drawerTitle = pathname === '/carbon-accounting/inventory' ? '碳核算清单详情' : pathname === '/asset-strategy/balance' ? '能效平衡详情' : `${String(drawer?.name ?? drawer?.source ?? drawer?.unit ?? '记录')}｜详情`;
  return <>{content}{toast && <div className={styles.toast}>✓　{toast}</div>}{modal && <Modal title={modalTitle} onClose={() => setModal(null)} onSave={() => { setModal(null); notify('保存成功'); }}><ContextModalFields kind={modal} /></Modal>}{drawer && <Drawer title={drawerTitle} onClose={() => setDrawer(null)} footer={<><Button onClick={() => { setDrawer(null); notify('记录已删除'); }}>删除</Button><Button primary onClick={() => { setDrawer(null); setModal('edit'); }}>编辑</Button><Button onClick={() => setDrawer(null)}>关闭</Button></>}><div className={styles.detailSummary}><b>{pathname === '/asset-strategy/balance' ? '用能平衡分析结果' : '核算对象基础信息'}</b><span>{pathname === '/asset-strategy/balance' ? '当前对象存在偏差，请结合能流和计量数据核查。' : '字段数据来自当前固定 Mock 核算任务。'}</span></div><div className={styles.detailGrid}>{Object.entries(drawer).map(([key, value]) => <div key={key}><span>{key}</span><b>{String(value)}</b></div>)}</div><h3>数据说明</h3><p className={styles.muted}>当前详情基于本地 Mock 数据展示，字段结构与主页面保持一致。</p></Drawer>}</>;
}

type PageProps = { notify: (message: string) => void; openModal: (kind: ActionKind) => void; openDrawer: (row: Row) => void; rows?: Row[]; setRows?: (rows: Row[]) => void };
function DataManagementPage({ pathname, activeTab, setActiveTab, notify, openModal, openDrawer }: PageProps & { pathname: string; activeTab: string; setActiveTab: (tab: string) => void }) {
  const isUnits = pathname.endsWith('/units'); const isTypes = pathname.endsWith('/energy-types'); const isRecords = pathname.includes('/energy-'); const isOps = pathname.endsWith('/operations'); const isDevices = pathname.endsWith('/devices');
  const title = isUnits ? '用能单元管理' : isTypes ? '能源品种管理' : isOps ? '运营数据管理' : isDevices ? '重点设备管理' : '能源数据管理';
  if (isRecords && !isUnits && !isTypes && !isOps && !isDevices) {
    const isCost = activeTab === '能源成本'; const isFlow = activeTab === '特殊能源关系';
    return <><FilterBar onQuery={() => notify('查询条件已更新')} onReset={() => notify('查询条件已重置')}><Field label="年度"><Select><option>2026</option><option>2025</option></Select></Field><Field label="分析类别"><Select><option>全部</option><option>生产单元</option><option>公辅系统</option></Select></Field><Field label="关键字"><input placeholder="请输入关键字" /></Field></FilterBar><Card><Tabs items={['能源消费', '能源成本', '特殊能源关系']} active={activeTab} onChange={setActiveTab} />{isCost ? <DataCostPage notify={notify} openModal={openModal} openDrawer={openDrawer} /> : isFlow ? <RelationPage notify={notify} openModal={openModal} openDrawer={openDrawer} /> : <ConsumptionPage notify={notify} openModal={openModal} openDrawer={openDrawer} />}</Card></>;
  }
  const data = isUnits ? units.map((unit, i) => ({ unit, level: i < 2 ? '一级' : '二级', type: i < 2 ? '生产单元' : '公辅系统' })) : isTypes ? energyTypes.map((energy, i) => ({ energy, unit: i === 0 ? 'kWh' : 't', factor: ['0.1229', '0.7143', '1.3300', '0.0341', '0.5714'][i], factorUnit: 'kgce/计量单位' })) : isOps ? units.map((unit, i) => ({ unit, category: '产量与业务量', name: i === 0 ? '熟料产量' : '产品产量', unitName: 't', value: `${(25000 - i * 1800).toLocaleString()}` })) : units.map((unit, i) => ({ unit, name: `重点设备${String.fromCharCode(65 + i)}`, type: '生产设备', energy: energyTypes[i], remark: '一期重点设备' }));
  return <><FilterBar onQuery={() => notify('查询条件已更新')} onReset={() => notify('已重置查询条件')} extra={<Button primary onClick={() => openModal('add')}>＋ 新增{isUnits ? '一级用能单元' : isTypes ? '能源品种' : isOps ? '运营数据' : '重点设备'}</Button>}><Field label="关键字"><input placeholder="请输入关键字" /></Field>{!isTypes && <Field label={isUnits ? '单元类型' : '分析类别'}><Select><option>全部</option><option>生产单元</option><option>公辅系统</option></Select></Field>}</FilterBar><Card className={styles.tableCard}><SectionTitle>{title}</SectionTitle><Table headers={Object.keys(data[0]).map((key) => ({ unit: '用能单元/计量单位', level: '层级', type: '单元类型', energy: '能源品种', name: '名称', factor: '折标系数', factorUnit: '折标单位', category: '指标类别', unitName: '单位', value: '年度值', remark: '备注' }[key] ?? key)).concat(['操作'])} rows={data.map((row) => ({ ...row, 操作: '查看　编辑　删除' }))} onRow={openDrawer} /></Card></>;
}
function ConsumptionPage({ openModal, openDrawer }: PageProps) { return <><div className={styles.subToolbar}><div className={styles.levelTabs}><button className={styles.tabActive}>全部（12）</button><button>一级用能单元（5）</button><button>二级用能单元（7）</button></div><Button primary onClick={() => openModal('add')}>＋ 新增能源消费</Button></div><Table headers={['归属范围', '归属层级', '分析类别', '能源品种', '单位', '数据进度', '年度合计', '操作']} rows={consumptionRows.map((row) => ({ ...row, 操作: '月度明细　编辑　删除' }))} onRow={openDrawer} /><div className={styles.note}>说明：年度合计由月度数据自动汇总；支持按月填报或仅填年度值。</div><div className={styles.tableFooter}>共 12 条　　‹　1　2　3　›</div></>; }
function DataCostPage({ openModal, openDrawer }: PageProps) { const rows = energyTypes.map((energy, i) => ({ energy, '1月成本（万元）': [6240, 2340, 1260, 488, 209][i], '2月': [6010, 2280, 1230, 475, 210][i], '12月': [6510, 2430, 1310, 502, 225][i], '年度合计（万元）': [74800, 27800, 15100, 5800, 2500][i], 操作: '编辑　删除' })); return <><div className={styles.subToolbar}><span className={styles.muted}>年度成本由 1—12 月数据自动汇总</span><Button primary onClick={() => openModal('add')}>＋ 新增成本数据</Button></div><Table headers={Object.keys(rows[0])} rows={rows} onRow={openDrawer} /><div className={styles.tableFooter}>共 5 条　　‹　1　›</div></>; }
function RelationPage({ openModal, openDrawer }: PageProps) { const rows = [{ type: '能源转换', unit: '余热发电系统', input: '余热', output: '电力', target: '全厂使用', status: '正常', 操作: '查看引用　编辑　删除' }, { type: '回收利用', unit: '回收热水利用', input: '回收热水', output: '蒸汽', target: '生产单元B', status: '正常', 操作: '查看引用　编辑　删除' }, { type: '外部输出', unit: '余热发电系统', input: '电力', output: '—', target: '企业外部', status: '待确认', 操作: '查看引用　编辑　删除' }]; return <><div className={styles.subToolbar}><span className={styles.muted}>普通能源分配由能源消费归属范围自动形成。</span><Button primary onClick={() => openModal('add')}>＋ 新增特殊能源关系</Button></div><Table headers={Object.keys(rows[0])} rows={rows} onRow={openDrawer} /></>; }

function EnergyQueryPage({ notify, openDrawer }: PageProps) { const rows = [{ no: 1, category: '电力', energy: '外购电力', quantity: '5,380,000', unit: 'kWh', tce: '5,160', share: '62.0%', yoy: '+2.8%', mom: '+1.2%', 操作: '查看' }, { no: 2, category: '燃料', energy: '天然气', quantity: '610,000', unit: 'Nm³', tce: '1,980', share: '24.0%', yoy: '+1.6%', mom: '+0.9%', 操作: '查看' }, { no: 3, category: '热力', energy: '蒸汽', quantity: '8,250', unit: 'GJ', tce: '760', share: '9.0%', yoy: '-0.8%', mom: '+0.3%', 操作: '查看' }]; return <><FilterBar onQuery={() => notify('能耗查询结果已更新')} onReset={() => notify('筛选条件已重置')} extra={<Button onClick={() => notify('明细导出成功')}>⇩ 导出明细</Button>}><Field label="统计周期"><span className={styles.segment}><button className={styles.segmentActive}>月度</button><button>年度</button></span></Field><Field label="时间"><input value="2026年6月" readOnly /></Field><Field label="用能单元"><Select><option>生产车间A</option><option>全企业</option></Select></Field></FilterBar><KpiGrid items={[['♨', '综合能耗', '5,160', 'tce', '同比 +2.8%'], ['↗', '同比', '+2.8%', '', ''], ['◎', '环比', '+1.2%', '', '']]} /><div className={styles.twoColumns}><Card><SectionTitle>能源消费趋势（2026年1-6月）</SectionTitle><BarChart values={[3800, 4020, 4330, 4560, 4860, 5160]} labels={['1月', '2月', '3月', '4月', '5月', '6月']} /></Card><Card><SectionTitle>能源结构</SectionTitle><Donut values={[3199, 1240, 465, 256]} colors={['#14aa72', '#2878ff', '#ff9d24', '#7657f6']} center="5,160" labels={['电力', '燃料', '热力', '其他']} /></Card></div><Card className={styles.tableCard}><SectionTitle>能源消费明细（生产车间A｜2026年6月）</SectionTitle><Table headers={Object.keys(rows[0]).map((key) => ({ no: '序号', category: '能源类别', energy: '能源品种', quantity: '实物量', unit: '单位', tce: '折标煤（tce）', share: '占比', yoy: '同比', mom: '环比', 操作: '操作' }[key] ?? key))} rows={rows} onRow={openDrawer} /></Card></>; }
function KpiGrid({ items }: { items: string[][] }) { return <div className={styles.kpiGrid}>{items.map(([icon, label, value, unit, sub]) => <Kpi key={label} icon={icon} label={label} value={value} unit={unit} sub={sub} />)}</div>; }

function IntensityPage({ notify, openDrawer }: PageProps) { const rows = [{ no: 1, name: '单位产品综合能耗', value: '91.8', unit: 'kgce/t', yoy: '↓ -2.3%', status: '可用', 操作: '查看详情' }, { no: 2, name: '单位产品电耗', value: '76.5', unit: 'kWh/t', yoy: '↓ -3.1%', status: '可用', 操作: '查看详情' }, { no: 3, name: '单位产值综合能耗', value: '0.351', unit: 'tce/万元', yoy: '↑ +1.1%', status: '可用', 操作: '查看详情' }, { no: 4, name: '单位增加值综合能耗', value: '—', unit: 'tce/万元', yoy: '—', status: '待补充', 操作: '去补充' }, { no: 5, name: '单位营业收入电耗', value: '152.3', unit: 'kWh/万元', yoy: '↓ -2.0%', status: '需核验', 操作: '查看问题' }]; return <><FilterBar onQuery={() => notify('指标结果已更新')} onReset={() => notify('筛选条件已重置')} extra={<Button onClick={() => notify('指标明细台账已导出')}>⇩ 导出明细台账</Button>}><Field label="分析年度"><input value="2026" readOnly /></Field><Field label="组织范围"><Select><option>全厂</option><option>生产车间A</option></Select></Field></FilterBar><Card className={styles.tableCard}><SectionTitle action={<span className={styles.muted}>共生成 5 项指标，其中 4 项可用，1 项待补充</span>}>指标结果明细</SectionTitle><Table headers={['序号', '指标名称', '数值', '单位', '同比', '结果状态', '操作']} rows={rows.map((row) => ({ ...row, 结果状态: row.status }))} onRow={openDrawer} /></Card><Card className={styles.infoNote}>ⓘ　说明：指标由能源数据与运营数据自动计算，支持查看指标结果与数据来源。</Card></>; }
function BenchmarkPage({ notify, openDrawer }: PageProps) { const rows = [{ object: '全厂', type: '企业', name: '单位产值综合能耗', unit: 'tce/万元', actual: '0.351', target: '0.340', deviation: '+3.2%', status: '未达标' }, { object: '生产单元A', type: '用能单元', name: '单位产品综合能耗', unit: 'kgce/t', actual: '91.8', target: '90.0', deviation: '+2.0%', status: '未达标' }, { object: '生产单元A', type: '用能单元', name: '单位产品电耗', unit: 'kWh/t', actual: '76.5', target: '78.0', deviation: '-1.9%', status: '达标' }, { object: '余热发电系统', type: '用能单元', name: '能源转换效率', unit: '%', actual: '85.7', target: '84.0', deviation: '+2.0%', status: '达标' }]; return <><FilterBar onQuery={() => notify('对标数据已更新')} onReset={() => notify('筛选条件已重置')} extra={<Button onClick={() => notify('对标值设置已打开')}>对标值设置</Button>}><Field label="分析年度"><Select><option>2026年</option><option>2025年</option></Select></Field><Field label="对象类型"><span className={styles.segment}><button className={styles.segmentActive}>全部</button><button>用能单元</button><button>产品</button><button>设备</button></span></Field><Field label="指标"><Select><option>全部</option><option>单位产品综合能耗</option></Select></Field><Field label="时间粒度"><Select><option>月度</option><option>年度</option></Select></Field></FilterBar><Card><SectionTitle>指标趋势（单位：kgce/t）<span className={styles.inlineMeta}>当前值 91.8　|　目标值 90.0　|　偏差率 <b className={styles.negative}>+2.0%</b></span></SectionTitle><LineChart actual={[89.2, 87.5, 88.6, 90.1, 91.3, 92.7, 95.6, 94.8, 93.7, 92.1, 90.5, 91.8]} target={90} labels={['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']} color="#2878ff" /></Card><Card className={styles.tableCard}><SectionTitle>指标对标明细（2026年）</SectionTitle><Table headers={Object.keys(rows[0])} rows={rows} onRow={openDrawer} /></Card></>; }
function FlowPage({ notify, openDrawer }: PageProps) { const rows = [{ type: '直接消费', input: '外购电力', relation: '—', target: '生产单元A', tce: '3,780', share: '28.4%', 操作: '查看来源' }, { type: '直接消费', input: '外购电力', relation: '—', target: '公辅系统', tce: '1,103', share: '8.3%', 操作: '查看来源' }, { type: '能源转换', input: '余热', relation: '余热发电系统→电力', target: '全厂使用', tce: '960', share: '7.2%', 操作: '查看关系' }, { type: '外部输出', input: '电力', relation: '余热发电系统', target: '企业外部', tce: '340', share: '2.6%', 操作: '查看关系' }]; return <><FilterBar onQuery={() => notify('能流数据已更新')} onReset={() => notify('筛选条件已重置')}><Field label="分析年度"><Select><option>2026年</option></Select></Field><Field label="组织范围"><Select><option>全厂</option></Select></Field><Field label="时间粒度"><Select><option>月度</option><option>年度</option></Select></Field><Field label="月份"><Select><option>6月</option><option>5月</option></Select></Field></FilterBar><KpiGrid items={[['⇥', '能源输入量', '13,320', 'tce', ''], ['✓', '已分配能源量', '12,980', 'tce', ''], ['⚠', '未分配能源量', '340', 'tce', ''], ['◔', '能源分配率', '97.4', '%', '']]} /><Card><Tabs items={['能流图', '能源平衡表']} active="能流图" onChange={() => undefined} /><FlowDiagram /></Card><div className={styles.twoColumns}><Card className={styles.tableCard}><SectionTitle>重点用能单元 TOP5</SectionTitle><Table headers={['排名', '用能单元', '折标量（tce）', '占比']} rows={units.map((unit, i) => ({ 排名: i + 1, 用能单元: unit, '折标量（tce）': [6220, 3480, 2300, 980, 340][i].toLocaleString(), 占比: `${[46.6, 26.1, 17.2, 7.3, 2.6][i]}%` }))} /></Card><Card className={styles.tableCard}><SectionTitle>能源流向明细</SectionTitle><Table headers={Object.keys(rows[0])} rows={rows} onRow={openDrawer} /></Card></div></>; }

function CarbonPreviewPage({ notify, openDrawer }: PageProps) { const rows = [{ border: '直接排放', source: '天然气燃烧', activity: '天然气消耗量', emission: '3,102.45', share: '24.67%' }, { border: '购入电力与热力产生的排放', source: '外购电力', activity: '外购电量', emission: '9,025.34', share: '71.79%' }, { border: '直接排放', source: '柴油燃烧', activity: '柴油消耗量', emission: '278.00', share: '2.21%' }, { border: '直接排放', source: '工业过程排放', activity: '熟料产量', emission: '174.66', share: '1.39%' }]; return <><Card className={styles.taskBanner}><b>当前核算任务：</b>2026年度组织温室气体核算 <Tag tone="green">通用工业企业</Tag><Tag tone="green">GB/T 32150—2025</Tag><Button onClick={() => notify('核算设置已打开')}>⚙ 核算设置</Button></Card><KpiGrid items={[['◒', '温室气体排放总量', '12,580.45', 'tCO₂e', '较上年 ↓ 2.35%'], ['▥', '直接排放', '3,102.45', 'tCO₂e', '占比 24.67%'], ['ϟ', '购入电力与热力产生的排放', '9,025.34', 'tCO₂e', '占比 71.79%'], ['▥', '排放强度', '0.68', 'tCO₂e/单位', '较上年 ↓ 2.40%']]}/><div className={styles.threeColumns}><Card><SectionTitle>排放构成（按核算边界）</SectionTitle><Donut values={[3102, 9025, 453]} colors={['#16a56e', '#4d96f7', '#cdd4db']} center="12,580" labels={['直接排放', '购入电力与热力', '其他间接排放']} /></Card><Card><SectionTitle>排放趋势（近5年）</SectionTitle><BarChart values={[11320, 11845, 12120, 12887, 12580]} labels={['2022', '2023', '2024', '2025', '2026']} color="#7bc9a9" /></Card><Card><SectionTitle>主要排放源排行</SectionTitle><Table headers={['排名', '排放源', '排放量', '占比']} rows={rows.map((row, i) => ({ 排名: i + 1, 排放源: row.source, 排放量: row.emission, 占比: row.share }))} /></Card></div><Card className={styles.tableCard}><SectionTitle>主要排放源明细</SectionTitle><Table headers={Object.keys(rows[0])} rows={rows} onRow={openDrawer} /></Card></>; }

function InventoryPage({ notify, openModal, openDrawer }: PageProps) { const localRows = inventoryRows; const groups = Array.from(new Set(localRows.map((row) => String(row.group)))); return <><Card className={styles.taskBanner}><b>当前核算任务：</b>2026年度组织温室气体核算 <Tag>通用工业企业</Tag><span className={styles.spacer} /><Button onClick={() => notify('核算设置已打开')}>⚙ 核算设置</Button><Button primary onClick={() => openModal('factor')}>⊕ 新增排放源</Button></Card><FilterBar onQuery={() => notify('清单已筛选')} onReset={() => notify('筛选条件已重置')}><Field label="搜索排放源"><input placeholder="搜索排放源" /></Field><Field label="核算边界"><Select><option>全部</option>{groups.map((group) => <option key={group}>{group}</option>)}</Select></Field></FilterBar><Card className={styles.groupCard}>{groups.map((group) => <div className={styles.inventoryGroup} key={group}><div className={styles.groupHead}>⌄　<b>{group}</b><span>（{localRows.filter((row) => row.group === group).length}）</span></div><Table headers={['温室气体源类型', '排放源', '活动数据', '排放量（tCO₂e）', '操作']} rows={localRows.filter((row) => row.group === group).map((row) => ({ type: row.type, source: row.source, activity: <span>{row.activity}<small className={styles.subText}>{row.origin}</small></span>, emission: row.emission, 操作: row.missing ? '补充数据　⋮' : '查看　编辑　⋮' } as unknown as Row))} onRow={openDrawer} /></div>)}</Card></>; }
function SupportPage({ notify, openDrawer }: PageProps) { const [tab, setTab] = useState('排放源支撑材料'); const rows = inventoryRows.map((row) => ({ 边界: row.group, 排放源: row.source, 活动数据: row.activity, 数据来源: row.origin, 支撑材料: row.missing ? '1 份' : '2 份', 状态: row.missing ? '待补充' : '已上传', 操作: '查看　材料管理' })); return <><Card className={styles.taskBanner}><b>当前核算任务：</b>2026年度组织温室气体核算 <Tag>通用工业企业</Tag><span className={styles.spacer} /><Button onClick={() => notify('已返回碳核算清单')}>返回碳核算清单</Button></Card><Card><Tabs items={['核算基础材料', '排放源支撑材料']} active={tab} onChange={setTab} /><FilterBar onQuery={() => notify('支撑材料已筛选')} onReset={() => notify('筛选条件已重置')}><Field label="搜索"><input placeholder="搜索排放源、数据项或材料名称" /></Field><Field label="状态"><Select><option>全部</option><option>已上传</option><option>待补充</option></Select></Field></FilterBar><Table headers={Object.keys(rows[0])} rows={tab === '核算基础材料' ? rows.slice(0, 3) : rows} onRow={openDrawer} /></Card></>; }
function FactorsPage({ notify, openModal, openDrawer }: PageProps) { const [tab, setTab] = useState('全部因子（128）'); const rows = factorRows.filter((row) => tab.startsWith('全部') || String(row.type).includes(tab.split('（')[0].replace('因子', ''))).map((row) => ({ ...row, 操作: '查看　编辑' })); return <><Card className={styles.infoNote}>因子库用于碳排放核算中的碳排放因子管理与引用，支持按标准来源分类管理。</Card><FilterBar onQuery={() => notify('因子查询完成')} onReset={() => notify('筛选条件已重置')} extra={<><Button onClick={() => notify('批量导入弹窗已打开')}>▦ 批量导入</Button><Button primary onClick={() => openModal('add')}>▣ 新增因子</Button></>}><Field label="搜索"><input placeholder="搜索因子名称/能源品种/排放源" /></Field><Field label="能源/物料类型"><Select><option>全部</option><option>天然气</option><option>电力</option></Select></Field><Field label="标准来源"><Select><option>全部</option><option>GB/T 32151-2023</option></Select></Field></FilterBar><Card className={styles.tableCard}><Tabs items={['全部因子（128）', '默认因子（98）', '实测因子（18）', '停用因子（12）']} active={tab} onChange={setTab} /><Table headers={Object.keys(rows[0])} rows={rows} onRow={openDrawer} /></Card></>; }

function BalancePage({ notify, openDrawer }: PageProps) { const rows = units.map((unit, i) => ({ 用能单元: unit, '能源输入量（tce）': [8900, 6700, 4950, 3950, 3950][i].toLocaleString(), '终端有效利用量（tce）': [6320, 4650, 3330, 2880, 2640][i].toLocaleString(), '回收利用量（tce）': [1230, 780, 520, 1020, 310][i].toLocaleString(), '外部输出量（tce）': [860, 570, 420, 100, 360][i].toLocaleString(), '平衡偏差（tce）': [490, 700, 680, -50, 640][i].toLocaleString(), 偏差率: ['5.5%', '10.4%', '13.7%', '-1.3%', '16.2%'][i], 状态: i === 3 ? '正常' : i === 0 ? '关注' : '异常', 操作: '查看详情' })); return <><FilterBar onQuery={() => notify('平衡数据已更新')} onReset={() => notify('筛选条件已重置')} extra={<Button onClick={() => notify('平衡报告已导出')}>⇩ 导出报告</Button>}><Field label="分析周期"><span className={styles.segment}><button className={styles.segmentActive}>月度</button><button>年度</button></span></Field><Field label="年份"><Select><option>2026年</option></Select></Field><Field label="月份"><Select><option>6月</option></Select></Field><Field label="统计范围"><Select><option>全企业</option></Select></Field></FilterBar><KpiGrid items={[['⇥', '能源输入量', '28,450', 'tce', '同比 +3.6%'], ['✓', '终端有效利用量', '19,820', 'tce', '占比 69.7%'], ['↻', '回收利用量', '3,860', 'tce', '占比 13.6%'], ['↗', '外部输出量', '3,130', 'tce', '占比 11.0%'], ['⚠', '平衡偏差', '1,640', 'tce', '偏差率 6.1%']]}/><div className={styles.twoColumns}><Card><SectionTitle>能效平衡总览</SectionTitle><FlowDiagram /></Card><Card><SectionTitle>关键偏差对象 TOP5</SectionTitle><div className={styles.rankList}>{units.map((unit, i) => <div key={unit}><b>{i + 1}</b><span>{unit}</span><div className={styles.rankTrack}><i style={{ width: `${100 - i * 17}%` }} /></div><strong>{[860, 520, 300, 220, 150][i]}</strong><em>{['8.9%', '6.3%', '5.8%', '4.2%', '3.1%'][i]}</em></div>)}</div></Card></div><Card className={styles.tableCard}><SectionTitle>用能单元平衡清单</SectionTitle><Table headers={Object.keys(rows[0])} rows={rows} onRow={openDrawer} /></Card><AiCards title="AI优化建议" notify={notify} /></>; }
function AnalysisPage({ notify }: PageProps) { return <><FilterBar onQuery={() => notify('分析结果已更新')} onReset={() => notify('筛选条件已重置')}><Field label="分析周期"><span className={styles.segment}><button className={styles.segmentActive}>月度</button><button>年度</button></span></Field><Field label="年份"><Select><option>2026年</option></Select></Field><Field label="月份"><Select><option>6月</option></Select></Field><Field label="统计范围"><Select><option>全企业</option></Select></Field></FilterBar><KpiGrid items={[['◔', '能源消费总量', '12,580', 'tce', '同比 +2.3%'], ['◉', '综合能源成本', '10,837', '万元', '同比 +2.3%'], ['↗', '单位产品综合能耗', '97.6', 'kgce/t', '同比 -0.7%']]}/><div className={styles.twoColumns}><Card><SectionTitle>能源消费结构</SectionTitle><Donut values={[7692, 3546, 1734, 226, 100]} colors={['#3b82f6', '#35b99a', '#ff9d24', '#7d61e8', '#9ba7b6']} center="12,580" labels={['煤炭', '外购电力', '替代燃料', '天然气', '其他']} /></Card><Card><SectionTitle>能源成本结构</SectionTitle><BarChart values={[6240, 2340, 1260, 488, 209]} labels={['煤炭', '外购电力', '替代燃料', '天然气', '其他']} color="#2878ff" /></Card></div><Card className={styles.tableCard}><SectionTitle>重点用能单元分析</SectionTitle><Table headers={['用能单元', '能源消费量（tce）', '占比', '能源成本（万元）', '同比变化', '关注建议']} rows={units.map((unit, i) => ({ 用能单元: unit, '能源消费量（tce）': [6320, 4650, 3330, 2880, 2640][i].toLocaleString(), 占比: ['50.2%', '37.0%', '26.5%', '22.9%', '21.0%'][i], '能源成本（万元）': [2450, 1830, 1120, 760, 520][i].toLocaleString(), 同比变化: ['+2.8%', '+1.6%', '-0.4%', '-1.2%', '+1.9%'][i], 关注建议: ['重点关注', '关注', '一般关注', '一般关注', '关注'][i] }))} /></Card><AiCards title="AI分析建议" notify={notify} /></>; }
function BudgetPage({ notify, openModal, openDrawer }: PageProps) { const [tab, setTab] = useState('能源预算管理'); const carbon = tab === '碳排放预算管理'; const rows = units.slice(0, 4).map((unit, i) => ({ 管理对象: i === 0 ? '全企业' : unit, 年度目标: carbon ? ['95,000', '42,000', '31,000', '22,000'][i] : ['120,600', '48,000', '39,000', '33,600'][i], 当前累计: carbon ? ['51,200', '23,800', '16,600', '10,800'][i] : ['65,000', '28,000', '19,000', '18,000'][i], 预计全年: carbon ? ['99,500', '45,200', '30,300', '24,000'][i] : ['125,600', '52,500', '38,200', '34,900'][i], 偏差: carbon ? ['+4,500', '+3,200', '-700', '+2,000'][i] : ['+5,000', '+4,500', '-800', '+1,300'][i], 状态: i === 0 ? '超预算风险' : i === 2 ? '正常' : '关注' })); return <><FilterBar onQuery={() => notify('预算数据已更新')} onReset={() => notify('筛选条件已重置')} extra={<Button primary onClick={() => openModal('budget')}>目标预算配置</Button>}><Field label="管理周期"><Select><option>2026年</option></Select></Field><Field label="统计范围"><Select><option>全企业</option></Select></Field></FilterBar><Card><Tabs items={['能源预算管理', '碳排放预算管理']} active={tab} onChange={setTab} /><div className={styles.budgetSummary}><Kpi icon="◎" label="年度目标" value={carbon ? '95,000' : '120,600'} unit={carbon ? 'tCO₂' : 'tce'} /><Kpi icon="▥" label="当前累计" value={carbon ? '51,200' : '65,000'} unit={carbon ? 'tCO₂' : 'tce'} /><Kpi icon="↗" label="预计全年" value={carbon ? '99,500' : '125,600'} unit={carbon ? 'tCO₂' : 'tce'} /><Kpi icon="⚠" label="预测偏差" value={carbon ? '+4,500' : '+5,000'} unit={carbon ? 'tCO₂' : 'tce'} tone="red" /><Kpi icon="◉" label="预算执行状态" value="超预算风险" unit="" tone="red" /></div><Card className={styles.innerCard}><SectionTitle action={<Button primary onClick={() => notify('已根据最新数据重新预测')}>↻ 重新预测</Button>}>年度预算累计趋势</SectionTitle><LineChart actual={carbon ? [12, 21, 29, 36, 44, 51] : [20, 31, 41, 50, 59, 68]} forecast={carbon ? [51, 61, 71, 80, 89, 99] : [68, 78, 88, 98, 108, 130]} target={carbon ? 95 : 120} labels={['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']} /></Card><Card className={styles.tableCard}><SectionTitle>预算执行分析</SectionTitle><Table headers={Object.keys(rows[0])} rows={rows} onRow={openDrawer} /></Card><AiCards title="AI分析建议" notify={notify} /></Card></>; }
function AssetsPage({ notify, openModal, openDrawer }: PageProps) { const rows = [{ type: '碳配额', cycle: '2026年度', source: '政府分配', amount: '95,000', used: '56,000', remaining: '39,000', 操作: '编辑　查看凭证' }, { type: 'CCER', cycle: '2026年度', source: '市场购买', amount: '5,000', used: '0', remaining: '5,000', 操作: '编辑　查看凭证' }, { type: '绿证折算减排量', cycle: '2026年度', source: '内部转化', amount: '1,200', used: '0', remaining: '1,200', 操作: '待确认详情' }]; return <><FilterBar onQuery={() => notify('资产数据已更新')} onReset={() => notify('筛选条件已重置')} extra={<><Button primary onClick={() => openModal('asset')}>录入碳资产</Button><Button onClick={() => openModal('estimate')}>新周期配额测算</Button></>}><Field label="履约周期"><Select><option>2026年度</option></Select></Field><Field label="统计范围"><Select><option>全企业</option></Select></Field></FilterBar><Card><SectionTitle>当前履约状态</SectionTitle><div className={styles.assetKpis}><Kpi icon="▣" label="已分配配额" value="95,000" unit="tCO₂" tone="blue" /><Kpi icon="✓" label="已使用配额" value="56,000" unit="tCO₂" /><Kpi icon="☁" label="CCER可用量" value="5,000" unit="tCO₂" tone="purple" /><Kpi icon="▥" label="预计全年排放" value="105,000" unit="tCO₂" tone="orange" /><Kpi icon="⚠" label="预计缺口" value="5,000" unit="tCO₂" tone="red" /></div><div className={styles.progressLabel}>配额与预计排放对比 <div className={styles.progressBar}><i /><i /><i /></div><span>已使用配额　56,000 tCO₂（53.3%）　 剩余可用资产　44,000 tCO₂（41.9%）　预计缺口　5,000 tCO₂（4.8%）</span></div></Card><div className={styles.twoColumns}><Card className={styles.tableCard}><SectionTitle>碳资产台账</SectionTitle><Table headers={Object.keys(rows[0])} rows={rows} onRow={openDrawer} /></Card><Card><SectionTitle>履约缺口趋势</SectionTitle><LineChart actual={[12, 25, 34, 44, 53, 62]} forecast={[62, 75, 88, 103, 118, 135]} target={100} labels={['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']} /></Card></div><Card><SectionTitle>新周期配额测算</SectionTitle><div className={styles.cycleGrid}><Kpi icon="◎" label="基准历史排放" value="98,500" unit="tCO₂" /><Kpi icon="▣" label="初步测算配额" value="96,000" unit="tCO₂" /><Kpi icon="↗" label="较本周期变化" value="+1.1" unit="%" tone="blue" /><Button onClick={() => openModal('estimate')}>查看测算说明 ＞</Button></div></Card><AiCards title="AI分析建议" notify={notify} /></>; }
function AiCards({ title, notify }: { title: string; notify: (message: string) => void }) { return <Card className={styles.aiCard}><SectionTitle action={<Button onClick={() => notify('报告已导出')}>⇩ 导出报告</Button>}>{title}</SectionTitle><div className={styles.aiGrid}><div><b>①　风险识别</b><p>发现重点对象存在偏差或预算风险，建议优先关注高耗能单元。</p><a onClick={() => notify('详情抽屉已打开')}>查看详情 ＞</a></div><div><b>②　偏差原因</b><p>可能与生产负荷、设备效率波动或数据缺失有关。</p><a onClick={() => notify('原因分析已打开')}>查看原因分析 ＞</a></div><div><b>③　调整建议</b><p>建议结合后续生产计划优化运行策略，持续跟踪目标执行情况。</p><a onClick={() => notify('优化方案已生成')}>生成优化方案 ＞</a></div></div></Card>; }
