import { useMemo, useState, type ReactNode } from 'react';
import { usePageHeaderActions } from '../../components/PageHeaderActionsContext';
import styles from './SupplierCarbonManagement.module.css';

type Status = '完整' | '待补碳数据' | '待补证明';
type SupplierRecord = { id:number; supplier:string; site:string; material:string; category:string; spec:string; year:string; quantity:string; unit:string; footprint?:string; footprintUnit:string; scope:string; contact:string; supports:number; status:Status };
type Delivery = { id:number; product:string; spec:string; year:string; scope:string; value:string; receiver:string; method:string; time:string };
const categories = ['金属材料', '化工原料', '电子组件', '包装材料', '高分子材料'];
const recordsSeed: SupplierRecord[] = [
  {id:1,supplier:'华东特钢有限公司',site:'江苏常州生产基地',material:'热轧钢卷',category:'金属材料',spec:'Q235B',year:'2026',quantity:'18,500',unit:'t',footprint:'1.82',footprintUnit:'kgCO₂e/kg',scope:'摇篮到大门',contact:'王工',supports:2,status:'完整'},
  {id:2,supplier:'新源化工材料有限公司',site:'山东淄博工厂',material:'工业级碳酸钠',category:'化工原料',spec:'99.2%',year:'2026',quantity:'4,200',unit:'t',footprint:'0.74',footprintUnit:'kgCO₂e/kg',scope:'摇篮到大门',contact:'刘经理',supports:0,status:'待补证明'},
  {id:3,supplier:'恒智电子科技有限公司',site:'广东东莞工厂',material:'控制器总成',category:'电子组件',spec:'ECU-A8',year:'2026',quantity:'86,000',unit:'件',footprintUnit:'kgCO₂e/件',scope:'摇篮到大门',contact:'陈工',supports:1,status:'待补碳数据'},
  {id:4,supplier:'华南包装材料有限公司',site:'广东佛山基地',material:'瓦楞纸箱',category:'包装材料',spec:'五层BC楞',year:'2026',quantity:'860,000',unit:'个',footprint:'0.39',footprintUnit:'kgCO₂e/个',scope:'摇篮到大门',contact:'李主管',supports:1,status:'完整'},
  {id:5,supplier:'北方铝业股份有限公司',site:'内蒙古包头基地',material:'铝合金板材',category:'金属材料',spec:'6061-T6',year:'2026',quantity:'12,800',unit:'t',footprint:'6.45',footprintUnit:'kgCO₂e/kg',scope:'摇篮到大门',contact:'赵工',supports:2,status:'完整'},
  {id:6,supplier:'联创塑胶制品有限公司',site:'浙江宁波工厂',material:'工程塑料粒子',category:'高分子材料',spec:'PA66-GF30',year:'2026',quantity:'1,650',unit:'t',footprint:'3.21',footprintUnit:'kgCO₂e/kg',scope:'摇篮到大门',contact:'周经理',supports:0,status:'待补证明'},
];
const deliverySeed: Delivery[] = [{id:1,product:'工业变频器',spec:'VFD-75',year:'2026',scope:'摇篮到大门',value:'86.4 kgCO₂e/台',receiver:'华东新能源汽车有限公司',method:'上传至接收方平台',time:'2026-09-12 14:20'},{id:2,product:'电机控制器',spec:'MCU-X3',year:'2026',scope:'摇篮到大门',value:'42.8 kgCO₂e/件',receiver:'华南智能制造有限公司',method:'邮件发送',time:'2026-09-10 09:35'},{id:3,product:'动力电池托盘',spec:'BT-120',year:'2025',scope:'摇篮到坟墓',value:'128.6 kgCO₂e/套',receiver:'远景能源科技有限公司',method:'线下交付',time:'2026-08-28 16:10'}];
const products = [{product:'工业变频器',spec:'VFD-75',year:'2026',scope:'摇篮到大门（Cradle to Gate）',value:'86.4',unit:'kgCO₂e/台',report:'工业变频器_VFD-75_碳足迹报告_2026.pdf'},{product:'电机控制器',spec:'MCU-X3',year:'2026',scope:'摇篮到大门（Cradle to Gate）',value:'42.8',unit:'kgCO₂e/件',report:'电机控制器_MCU-X3_碳足迹报告_2026.pdf'}];

export function SupplierCarbonManagement() {
  const [tab,setTab] = useState<'collection'|'delivery'>('collection'); const [records,setRecords] = useState(recordsSeed); const [deliveries,setDeliveries] = useState(deliverySeed);
  const [year,setYear] = useState('2026'); const [keyword,setKeyword] = useState(''); const [category,setCategory] = useState(''); const [status,setStatus] = useState('');
  const [selected,setSelected] = useState<SupplierRecord|null>(null); const [selectedDelivery,setSelectedDelivery] = useState<Delivery|null>(null); const [modal,setModal] = useState<'collection'|'delivery'|null>(null); const [editing,setEditing] = useState<SupplierRecord|null>(null); const [editingDelivery,setEditingDelivery] = useState<Delivery|null>(null); const [deleteTarget,setDeleteTarget] = useState<{kind:'collection'|'delivery';id:number;name:string}|null>(null); const [product,setProduct] = useState(products[0].product);
  const filtered = useMemo(()=>records.filter(r=>(!year||r.year===year)&&(!keyword||`${r.supplier}${r.material}`.includes(keyword))&&(!category||r.category===category)&&(!status||r.status===status)),[records,year,keyword,category,status]);
  const closeModal=()=>{setModal(null);setEditing(null);setEditingDelivery(null)}; const saveRecord=()=>{setRecords(xs=>editing?xs.map(x=>x.id===editing.id?editing:x):[{...recordsSeed[0],id:Date.now(),supplier:'新录入供应商',material:'待完善材料',status:'待补碳数据',supports:0},...xs]);closeModal()}; const saveDelivery=()=>{const p=products.find(x=>x.product===product)??products[0]; const next={id:editingDelivery?.id??Date.now(),product:p.product,spec:p.spec,year:p.year,scope:'摇篮到大门',value:`${p.value} ${p.unit}`,receiver:editingDelivery?.receiver??'待完善接收方',method:editingDelivery?.method??'邮件发送',time:editingDelivery?.time??'2026-09-14 13:40'};setDeliveries(xs=>editingDelivery?xs.map(x=>x.id===editingDelivery.id?next:x):[next,...xs]);closeModal()}; const confirmDelete=()=>{if(!deleteTarget)return; if(deleteTarget.kind==='collection')setRecords(xs=>xs.filter(x=>x.id!==deleteTarget.id));else setDeliveries(xs=>xs.filter(x=>x.id!==deleteTarget.id));setDeleteTarget(null)};
  usePageHeaderActions(useMemo(()=><button className={styles.primary} onClick={()=>setModal(tab)}>＋ {tab==='collection'?'新增供应商碳数据':'新建交付记录'}</button>,[tab]));
  return <div className={styles.page}><div className={styles.tabs}><button className={tab==='collection'?styles.activeTab:''} onClick={()=>setTab('collection')}>上游 · 供应商碳数据</button><button className={tab==='delivery'?styles.activeTab:''} onClick={()=>setTab('delivery')}>下游 · 产品碳足迹交付</button></div>
    {tab==='collection'?<CollectionPage filtered={filtered} year={year} keyword={keyword} category={category} status={status} setYear={setYear} setKeyword={setKeyword} setCategory={setCategory} setStatus={setStatus} onSelect={setSelected} onEdit={r=>{setEditing(r);setModal('collection')}} onDelete={r=>setDeleteTarget({kind:'collection',id:r.id,name:r.material})} />:<DeliveryPage deliveries={deliveries} year={year} setYear={setYear} onSelect={setSelectedDelivery} onEdit={r=>{setEditingDelivery(r);setProduct(r.product);setModal('delivery')}} onDelete={r=>setDeleteTarget({kind:'delivery',id:r.id,name:r.product})} />}
    {modal&&<div className={styles.overlay} onClick={closeModal}><div className={styles.modal} onClick={e=>e.stopPropagation()}>{modal==='collection'?<CollectionForm record={editing} close={closeModal} save={saveRecord}/>:<DeliveryForm record={editingDelivery} product={product} setProduct={setProduct} close={closeModal} save={saveDelivery}/>}</div></div>}
    {selected&&<SupplierDrawer record={selected} close={()=>setSelected(null)} />}{selectedDelivery&&<DeliveryDrawer record={selectedDelivery} close={()=>setSelectedDelivery(null)} />}{deleteTarget&&<DeletePrompt name={deleteTarget.name} close={()=>setDeleteTarget(null)} confirm={confirmDelete} />}</div>;
}

function CollectionPage({filtered,year,keyword,category,status,setYear,setKeyword,setCategory,setStatus,onSelect,onEdit,onDelete}:{filtered:SupplierRecord[];year:string;keyword:string;category:string;status:string;setYear:(x:string)=>void;setKeyword:(x:string)=>void;setCategory:(x:string)=>void;setStatus:(x:string)=>void;onSelect:(r:SupplierRecord)=>void;onEdit:(r:SupplierRecord)=>void;onDelete:(r:SupplierRecord)=>void}) { return <><div className={styles.toolbar}><label>数据年度<select value={year} onChange={e=>setYear(e.target.value)}><option value="">全部</option><option>2026</option><option>2025</option></select></label><label className={styles.grow}>供应商名称 / 材料产品<input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="请输入供应商或材料/产品名称"/></label><Select label="材料/产品类别" value={category} options={['全部',...categories]} onChange={setCategory}/><Select label="数据状态" value={status} options={['全部','完整','待补碳数据','待补证明']} onChange={setStatus}/><button className={styles.primary}>⌕ 查询</button><button className={styles.button} onClick={()=>{setYear('2026');setKeyword('');setCategory('');setStatus('')}}>重置</button></div><div className={styles.stats}><Stat label="供应商数量" value={new Set(filtered.map(r=>r.supplier)).size} unit="家" tone="blue"/><Stat label="材料/产品数据" value={filtered.length} unit="条" tone="green"/><Stat label="已提供碳足迹" value={filtered.filter(r=>r.footprint).length} unit="条" tone="orange"/><Stat label="待补充数据" value={filtered.filter(r=>r.status!=='完整').length} unit="条" tone="purple"/></div><div className={styles.card}><div className={styles.cardHead}><b>供应商碳数据列表</b><span>一条记录对应“供应商 + 生产基地 + 材料/产品 + 数据年度”</span></div><div className={styles.tableWrap}><table><thead><tr>{['供应商名称','材料/产品','生产基地','数据年度','供应/采购量','碳足迹结果','生命周期边界','证明材料','数据状态','操作'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><b>{r.supplier}</b><small>联系人：{r.contact}</small></td><td><b>{r.material}</b><small>{r.category} · {r.spec}</small></td><td>{r.site}</td><td>{r.year}</td><td>{r.quantity} {r.unit}</td><td>{r.footprint?<><strong className={styles.footprint}>{r.footprint}</strong><small>{r.footprintUnit}</small></>:<span className={styles.missing}>—</span>}</td><td>{r.scope}</td><td>{r.supports?<span className={styles.link}>📎 {r.supports} 份</span>:<span className={styles.missing}>未上传</span>}</td><td><StatusTag status={r.status}/></td><td><button className={styles.textButton} onClick={()=>onSelect(r)}>查看</button><button className={styles.textButton} onClick={()=>onEdit(r)}>编辑</button><button className={`${styles.textButton} ${styles.deleteButton}`} onClick={()=>onDelete(r)}>删除</button></td></tr>)}</tbody></table></div><div className={styles.pager}>共 {filtered.length} 条<span>10 条/页　‹　<b>1</b>　2　›</span></div></div></> }
function DeliveryPage({deliveries,year,setYear,onSelect,onEdit,onDelete}:{deliveries:Delivery[];year:string;setYear:(x:string)=>void;onSelect:(r:Delivery)=>void;onEdit:(r:Delivery)=>void;onDelete:(r:Delivery)=>void}) { return <><div className={styles.toolbar}><label>数据年度<select value={year} onChange={e=>setYear(e.target.value)}><option value="">全部</option><option>2026</option><option>2025</option></select></label><label className={styles.grow}>产品名称<input placeholder="请输入产品名称"/></label><label className={styles.grow}>接收方名称<input placeholder="请输入接收方名称"/></label><button className={styles.primary}>⌕ 查询</button><button className={styles.button}>重置</button></div><div className={styles.stats}><Stat label="交付记录数" value={deliveries.length} unit="条" tone="blue"/><Stat label="已交付产品" value={3} unit="个" tone="green"/><Stat label="已交付客户" value={3} unit="家" tone="orange"/><Stat label="交付完成率" value={100} unit="%" tone="purple"/></div><div className={styles.card}><div className={styles.cardHead}><b>碳足迹交付记录</b><span>记录产品碳足迹报告向下游客户的交付情况</span></div><div className={styles.tableWrap}><table><thead><tr>{['产品名称','规格型号','数据年度','生命周期范围','碳足迹结果','接收方名称','交付方式','交付时间','操作'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{deliveries.map(r=><tr key={r.id}><td><b>{r.product}</b></td><td>{r.spec}</td><td>{r.year}</td><td>{r.scope}</td><td><strong className={styles.footprint}>{r.value}</strong></td><td>{r.receiver}</td><td>{r.method}</td><td>{r.time}</td><td><button className={styles.textButton} onClick={()=>onSelect(r)}>查看</button><button className={styles.textButton} onClick={()=>onEdit(r)}>编辑</button><button className={`${styles.textButton} ${styles.deleteButton}`} onClick={()=>onDelete(r)}>删除</button></td></tr>)}</tbody></table></div><div className={styles.pager}>共 {deliveries.length} 条<span>10 条/页　‹　<b>1</b>　›</span></div></div></> }

function CollectionForm({record,close,save}:{record:SupplierRecord|null;close:()=>void;save:()=>void}) { const val=(key:keyof SupplierRecord)=>record?.[key] as string|undefined; return <><ModalHead title={`${record?'编辑':'新增'}供应商碳数据`} sub="直接录入供应商提供的材料/产品碳数据及必要业务信息；暂无碳数据或证明材料时可先保存，后续补充。" close={close}/><div className={styles.modalBody}><Section title="一、基础信息"/><div className={styles.formGrid}><Field label={<Required>供应商名称</Required>} value={val('supplier')} placeholder="请输入供应商全称"/><Field label={<Required>生产基地</Required>} value={val('site')} placeholder="请输入生产基地或工厂"/><Field label={<Required>材料/产品</Required>} value={val('material')} placeholder="如：铝合金板材、控制器总成"/><Select label={<Required>材料/产品类别</Required>} value={val('category')??'金属材料'} options={categories}/><Field label="规格型号" value={val('spec')} placeholder="选填"/><Select label={<Required>数据年度</Required>} value={val('year')??'2026'} options={['2026','2025']}/><Field label="供应商联系人" value={val('contact')} placeholder="选填"/><Field label="数据期间" value="2026-01-01 至 2026-12-31"/></div><Section title="二、供应业务数据"/><div className={styles.info}>这里只保留用于供应链碳管理的必要业务数据，不在本页面展开供应商完整生产活动数据。</div><div className={styles.formGrid}><Field label={<Required>供应/采购量</Required>} value={val('quantity')} placeholder="请输入数量" type="number"/><Select label={<Required>数量单位</Required>} value={val('unit')??'t'} options={['t','kg','件','个','套']}/></div><Section title="三、材料/产品碳数据"/><div className={styles.formGrid}><Field label="碳足迹结果" value={val('footprint')} placeholder="暂无时可先不填" type="number" help="若暂未取得供应商碳足迹结果，保存后状态自动显示为“待补碳数据”。"/><Select label="结果单位" value={val('footprintUnit')??'kgCO₂e/kg'} options={['kgCO₂e/kg','kgCO₂e/件','kgCO₂e/个','kgCO₂e/套']}/><Select label="生命周期边界" value={val('scope')??'请选择'} options={['请选择','摇篮到大门（Cradle to Gate）','摇篮到坟墓（Cradle to Grave）']}/><Field label="核算标准/依据" placeholder="如：ISO 14067、EPD PCR"/><Select label="碳数据来源" value="请选择" options={['请选择','供应商提供','第三方核查报告','EPD/环境声明','内部核算']}/><Field label="报告/数据有效期" type="date"/></div><Section title="四、证明材料"/><Upload label="点击选择证明材料" hint="支持 PDF、XLSX、DOCX、JPG、PNG，可多选" multiple/><label className={styles.fullField}>备注<textarea placeholder="选填"/></label></div><ModalFoot close={close} submit={save} label="保存数据"/></> }
function DeliveryForm({record,product,setProduct,close,save}:{record:Delivery|null;product:string;setProduct:(x:string)=>void;close:()=>void;save:()=>void}) { const preview=products.find(x=>x.product===product)??products[0]; return <><ModalHead title={`${record?'编辑':'新建'}碳足迹交付记录`} close={close}/><div className={styles.modalBody}><div className={styles.info}>选择已完成并生成报告的产品碳足迹，登记接收方与交付方式；需要时可上传邮件回执、系统截图或签收单等凭证。</div><Section title="一、选择碳足迹报告"/><Select label={<Required>选择产品</Required>} value={`${product} · ${preview.spec}`} options={products.map(x=>`${x.product} · ${x.spec}`)} onChange={v=>setProduct(v.split(' · ')[0])}/><ProductPreview product={preview}/><Section title="二、接收方信息"/><div className={styles.formGrid}><Field label={<Required>接收方名称</Required>} value={record?.receiver} placeholder="请输入公司或单位名称"/><Field label={<Required>联系人</Required>} placeholder="请输入联系人姓名"/><Field label={<Required>联系方式</Required>} placeholder="手机、邮箱或企业账号"/><Select label={<Required>交付方式</Required>} value={record?.method??'邮件发送'} options={['邮件发送','上传至接收方平台','即时通讯发送','线下交付','其他方式']}/><Field label="交付时间" value={record?.time??'2026/09/14 13:40'}/><Field label="交付说明" placeholder="选填"/></div><Section title="三、交付凭证（可选）"/><Upload label="点击选择凭证" hint="可上传邮件回执、聊天截图、签收单等"/></div><ModalFoot close={close} submit={save} label={record?'保存修改':'确认创建'}/></> }
function ModalHead({title,sub,close}:{title:string;sub?:string;close:()=>void}) { return <div className={styles.modalHead}><div><b>{title}</b>{sub&&<small>{sub}</small>}</div><button onClick={close}>×</button></div> } function ModalFoot({close,submit,label}:{close:()=>void;submit:()=>void;label:string}) { return <div className={styles.modalFoot}><button className={styles.button} onClick={close}>取消</button><button className={styles.primary} onClick={submit}>{label}</button></div> } function Section({title}:{title:string}) { return <h3>{title}</h3> } function Required({children}:{children:string}) { return <>{children}<em className={styles.required}>*</em></> } function Field({label,value,placeholder,type='text',help}:{label:ReactNode;value?:string;placeholder?:string;type?:string;help?:string}) { return <label>{label}<input type={type} defaultValue={value} placeholder={placeholder}/>{help&&<small className={styles.help}>{help}</small>}</label> } function Select({label,value,options,onChange}:{label:ReactNode;value:string;options:string[];onChange?:(x:string)=>void}) { return <label>{label}<select value={value} onChange={e=>onChange?.(e.target.value)}>{options.map(x=><option key={x} value={x==='全部'?'':x}>{x}</option>)}</select></label> } function Upload({label,hint,multiple}:{label:string;hint:string;multiple?:boolean}) { return <label className={styles.upload}>☁<b>{label}</b><small>{hint}</small><input type="file" multiple={multiple}/></label> } function ProductPreview({product}:{product:(typeof products)[number]}) { return <div className={styles.productPreview}><div><b>{product.product}</b><p>规格型号： {product.spec}<br/>数据年度： {product.year}<br/>生命周期范围： {product.scope}<br/>报告文件： {product.report}</p></div><strong>{product.value}<small>{product.unit}</small></strong></div> }
function SupplierDrawer({record,close}:{record:SupplierRecord;close:()=>void}) { return <div className={styles.overlay} onClick={close}><aside className={styles.drawer} onClick={e=>e.stopPropagation()}><ModalHead title="供应商碳数据详情" close={close}/><div className={styles.drawerBody}>{record.status!=='完整'&&<div className={styles.warning}>当前记录仍有信息待补充，建议尽快取得供应商碳足迹结果或上传证明材料。</div>}<Detail title="基础信息" rows={[['供应商名称',record.supplier],['生产基地',record.site],['材料/产品',record.material],['材料/产品类别',record.category],['规格型号',record.spec],['数据年度',record.year],['供应商联系人',record.contact]]}/><Detail title="供应业务数据" rows={[['供应/采购量',`${record.quantity} ${record.unit}`]]}/><Detail title="材料/产品碳数据" rows={[['碳足迹结果',record.footprint?`${record.footprint} ${record.footprintUnit}`:'—'],['生命周期边界',record.scope],['证明材料',`${record.supports} 份`]]}/></div><ModalFoot close={close} submit={close} label="关闭"/></aside></div> }
function DeliveryDrawer({record,close}:{record:Delivery;close:()=>void}) { return <div className={styles.overlay} onClick={close}><aside className={styles.drawer} onClick={e=>e.stopPropagation()}><ModalHead title="交付记录详情" close={close}/><div className={styles.drawerBody}><Detail title="产品信息" rows={[['产品名称',record.product],['规格型号',record.spec],['数据年度',record.year],['生命周期范围',record.scope],['碳足迹结果',record.value]]}/><Detail title="交付信息" rows={[['接收方名称',record.receiver],['交付方式',record.method],['交付时间',record.time]]}/></div><ModalFoot close={close} submit={close} label="关闭"/></aside></div> }
function DeletePrompt({name,close,confirm}:{name:string;close:()=>void;confirm:()=>void}) { return <div className={styles.overlay} onClick={close}><div className={`${styles.modal} ${styles.deletePrompt}`} onClick={e=>e.stopPropagation()}><ModalHead title="删除记录" close={close}/><div className={styles.deletePromptBody}>确定删除“{name}”吗？删除后不可恢复。</div><ModalFoot close={close} submit={confirm} label="确认删除"/></div></div> }
function StatusTag({status}:{status:Status}) { return <span className={`${styles.tag} ${status==='完整'?styles.green:styles.orange}`}><i/>{status}</span> } function Stat({label,value,unit,tone}:{label:string;value:number;unit:string;tone:string}) { return <div className={`${styles.stat} ${styles[tone]}`}><div className={styles.statIcon}>{tone==='blue'?'企':tone==='green'?'材':tone==='orange'?'CO₂':'!'}</div><div><span>{label}</span><strong>{value}<small>{unit}</small></strong></div></div> } function Detail({title,rows}:{title:string;rows:string[][]}) { return <section className={styles.detail}><div className={styles.detailHead}>{title}</div>{rows.map(([k,v])=><div className={styles.detailRow} key={k}><span>{k}</span><b>{v}</b></div>)}</section> }
